const functions = require("firebase-functions"); // npm install firebase-functions
const admin = require("firebase-admin"); // npm install firebase-admin
const nodemailer = require("nodemailer"); // npm install nodemailer

// Initialize Firebase-Admin
admin.initializeApp();

// Register account in mailtrap.io/register/signup
let transporter = nodemailer.createTransport({
  host: "smtp.mailtrap.io",
  port: 2525,
  auth: {
    user: "", // generated by Mailtrap 
    pass: "" // generated by Mailtrap
  }
});

exports.emailSender = functions.https.onRequest((req, res) => {
  const mailOptions = {
    from: 'test.test.test', // Adding Sender Email
    to: req.query.dest, // Getting recipients email by query string
    subject: 'Email via Firebase', // Email Subject 
    text: 'sending message withOUT HTML!!', // Email content without HTML  
    html: '<h1> Email of Fire</h1>'  // Email Content with HTML 
  };

  return transporter.sendMail(mailOptions, (err, info) => {
    if (err) {
      return res.send(err.toString());
    }
    return res.send('Email sent without Errors!');
  });
});
